version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:5
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

