# Base Image
FROM python:3.9-slim as builder
WORKDIR /app

# Copy dependency file first for efficient caching
COPY requirements.txt .

# To prevent creating the .cache directory which is not needed in this stage
RUN pip install --no-cache-dir -r requirements.txt --target /app/deps

COPY . .

# Final distroless image
FROM gcr.io/distroless/python3-debian11
WORKDIR /app

# Copy dependencies from the builder stage
COPY --from=builder /app/deps /app/deps
COPY --from=builder /app .

# Set environmet variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="/app/deps"

# Expose the application port
EXPOSE 5000

# Run the application directly as it is a distroless image for python so python is pre-populated in CMD command
CMD ["run.py"]
