# Build Stage
FROM eclipse-temurin:17-jdk-alpine AS builder

# Labels
LABEL maintainer="abhayshrivastava830@gmail.com"
LABEL version="1.0"
LABEL description="A simple java application"

WORKDIR /app
COPY src/ /app/src/
RUN mkdir -p /app/out && javac -d /app/out /app/src/Main.java 

# Run Stage
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app/out

COPY --from=builder /app/out .

CMD ["java", "-cp", ".", "Main"]

